# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'

    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: docs
      fqdn: vctrs.r-lib.org
      on:
        branch: master
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1

