# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.1
- 3.2
- 3.3
- oldrel
- release

matrix:
  include:
  - r: devel
    after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'pkgdown::build_site()'

    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      local-dir: docs
      fqdn: vctrs.r-lib.org
      on:
        branch: master
        r: release
